project:
  type: book
  output-dir: docs

number-depth: 2

book:
  title: "KI als Hilfe zum Lehren und Lernen"
  author: "Roman Bartnik"
  description: "Dieses Skript ist eine frei verf√ºgbare Ressource, die dabei helfen soll, GenAI in Lehr- und Lernprozessen erfolgreich einzusetzen."
  date: "2025-12-05"
  page-navigation: true
  chapters:
    - index.qmd
    - kapitel01.qmd
    - kapitel02.qmd
    - kapitel03.qmd
    - kapitel04.qmd
    - kapitel05.qmd
    
  cover-image: images/logos/logo.svg
  image: images/logos/logo.svg
  search: true

  # GitHub integration + sidebar tools
  repo-url: https://github.com/TH-Koln-Bartnik/genai4teaching
  repo-branch: main
  repo-actions: [edit, issue, source]
  downloads: [pdf, epub]
  sharing: [twitter, linkedin]

  sidebar:
    style: "floating"

  page-footer:
    left: "Bartnik, R. (2025). Generative KI als Lehr- und Lernhilfe in der Hochschullehre. Online: https://th-koln-bartnik.github.io/genai4teaching/. https://doi.org/10.5281/zenodo.17868898"

format:
  pdf:
    toc: true
    number-sections: true
    colorlinks: true
    df-print: kable
  epub:
    toc: true
    df-print: kable
  html:
    toc: true
    toc-location: right
    toc-depth: 3
    number-sections: true
    section-bibliographies: true
    theme:
      light:
        - flatly
        - include/light.scss
      dark:
        - darkly
        - include/dark.scss
    css: [include/booktem.css, include/style.css, include/webex.css]
    df-print: kable
    code-link: true
    code-fold: false
    code-line-numbers: true
    code-overflow: wrap
    code-copy: hover
    highlight-style: a11y
    monofont: Fira Code
    mainfont: Open Sans
    include-after-body: [include/webex.js, include/script.js]

bibliography: references.json
csl: apa.csl
