project:
  type: book
  output-dir: docs
  resources:
    - downloads/**

number-depth: 4

book:
  title: "KI als Hilfe zum Lehren und Lernen (Beta-Version! Format wird noch optimiert)"
  author: "Roman Bartnik"
  description: "Dieses Skript ist eine frei verf√ºgbare Ressource (CC-BY-SA), die dabei helfen soll, GenAI in Lehr- und Lernprozessen erfolgreich einzusetzen (zu den Details der sehr weit definierten freien Nutzung siehe https://creativecommons.org/licenses/by-sa/4.0/)"
  date: "2025-12-31"
  page-navigation: true
  chapters:
    - index.qmd
    - kapitel01.qmd
    - kapitel02.qmd
    - kapitel03.qmd
    - kapitel04.qmd
    - kapitel05.qmd
    
  appendices:  # Hier beginnt der Anhang (wird automatisch A, B... nummeriert)
    - appendix01-prompt-ueberblick.qmd
    - appendix02-prompt-sammlung.qmd
    

  cover-image: images/logos/logo.svg
  image: images/logos/logo.svg
  search: true
  output-file: downloads/genai4teaching

  # GitHub integration + sidebar tools
  repo-url: https://github.com/TH-Koln-Bartnik/genai4teaching
  repo-branch: main
  repo-actions: [edit, issue, source]
  downloads: [pdf, epub]
  sharing: [twitter, linkedin]

  sidebar:
    style: "floating"

  page-footer:
    left: "Bartnik, R. (2025). Generative KI als Lehr- und Lernhilfe in der Hochschullehre. Online: https://th-koln-bartnik.github.io/genai4teaching/. https://doi.org/10.5281/zenodo.17868898"

format:
   html:
    toc: true
    toc-location: right
    toc-depth: 4
    toc-expand: 4
    number-sections: true
    section-bibliographies: true
    code-copy: true
    
    theme:
      light:
        - flatly
        - include/light.scss
      dark:
        - darkly
        - include/dark.scss
    css: [include/booktem.css, include/style.css, include/webex.css]
  
   pdf:
    documentclass: scrreprt
    number-sections: true

   epub:
    toc: true
  
bibliography: references.json
csl: apa.csl
